-- =========================================================
-- 0. XÓA DATABASE CŨ (NẾU CÓ) VÀ TẠO MỚI AN TOÀN
-- =========================================================
USE master;
GO

-- Ngắt các kết nối đang dở dang và xóa database cũ nếu đã tồn tại
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'E_SHOPPING')
BEGIN
    ALTER DATABASE E_SHOPPING SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE E_SHOPPING;
END
GO

-- Tạo mới database
CREATE DATABASE E_SHOPPING;
GO

-- Sử dụng database vừa tạo
USE E_SHOPPING;
GO

-- =========================================================
-- 1. TẠO TOÀN BỘ CÁC BẢNG (FULL DATABASE)
-- =========================================================

-- 1.1. Bảng Khách hàng
CREATE TABLE KHACHHANG (
    MAKH VARCHAR(10) PRIMARY KEY,
    HOTEN VARCHAR(100) NOT NULL,
    NGAYSINH DATE,
    CCCD VARCHAR(20) UNIQUE NOT NULL,
    DIACHI VARCHAR(255),
    DIENTHOAI VARCHAR(15),
    TENDANGNHAP VARCHAR(50) UNIQUE NOT NULL,
    MATKHAU VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE
);

-- 1.2. Bảng Nhóm sản phẩm
CREATE TABLE NHOMSANPHAM (
    MANHOM VARCHAR(10) PRIMARY KEY,
    TENNHOM VARCHAR(100) NOT NULL,
    MOTANHOM TEXT
);

-- 1.3. Bảng Sản phẩm
CREATE TABLE SANPHAM (
    MASP VARCHAR(20) PRIMARY KEY,
    TENSP VARCHAR(100) NOT NULL,
    NHASANXUAT VARCHAR(100),
    HINHANH VARCHAR(255),
    MOTASP TEXT,
    THONGSOKYTHUAT TEXT,
    GIABANHIENHANH DECIMAL(12,2) NOT NULL,
    TINHTRANG INT, 
    MANHOM VARCHAR(10),
    FOREIGN KEY (MANHOM) REFERENCES NHOMSANPHAM(MANHOM)
);

-- 1.4. Bảng Giỏ hàng
CREATE TABLE GIOHANG (
    MAKH VARCHAR(10),
    MASP VARCHAR(20),
    SOLUONG INT NOT NULL,
    PRIMARY KEY (MAKH, MASP),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON DELETE CASCADE,
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP) ON DELETE CASCADE
);

-- 1.5. Bảng Loại phiếu đặt hàng
CREATE TABLE PHIEUDATHANG (
    MALOAIPHIEU VARCHAR(10) PRIMARY KEY,
    TENLOAIPHIEU VARCHAR(50) NOT NULL,
    DONGIPHIVANCHUYEN DECIMAL(12,2) NOT NULL,
    THOIGIANXULY VARCHAR(50)
);

-- 1.6. Bảng Đơn hàng
CREATE TABLE DONHANG (
    SODDH VARCHAR(20) PRIMARY KEY,
    NGAYDATHANG DATETIME NOT NULL,
    TONGTRIGIA DECIMAL(12,2) NOT NULL,
    PHIGIAOHANG DECIMAL(12,2) DEFAULT 0,
    TENNGUOINHAN VARCHAR(100) NOT NULL,
    DIACHINHAN VARCHAR(255) NOT NULL,
    DIENTHOAINHAN VARCHAR(15) NOT NULL,
    MAKH VARCHAR(10),
    MALOAIPHIEU VARCHAR(10),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MALOAIPHIEU) REFERENCES PHIEUDATHANG(MALOAIPHIEU)
);

-- 1.7. Bảng Chi tiết đơn hàng
CREATE TABLE CHITIETDONHANG (
    SODDH VARCHAR(20),
    MASP VARCHAR(20),
    SOLUONG INT NOT NULL,
    DONGIA DECIMAL(12,2) NOT NULL,
    PRIMARY KEY (SODDH, MASP),
    FOREIGN KEY (SODDH) REFERENCES DONHANG(SODDH) ON DELETE CASCADE,
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

-- 1.8. Bảng Thanh toán thẻ tín dụng
CREATE TABLE THANHTOANTHE (
    MAGIAODICH VARCHAR(20) PRIMARY KEY,
    SODDH VARCHAR(20) UNIQUE,
    LOAITHE VARCHAR(20) NOT NULL,
    SOHIEUTHE VARCHAR(20) NOT NULL,
    NGAYHETHAN VARCHAR(10) NOT NULL,
    HOTENCHUTHE VARCHAR(100) NOT NULL,
    MASOANNINHCSV VARCHAR(4) NOT NULL,
    TRANGTHAITHANHTOAN VARCHAR(50) NOT NULL,
    FOREIGN KEY (SODDH) REFERENCES DONHANG(SODDH) ON DELETE CASCADE
)

USE E_SHOPPING;
GO

-- Mở rộng độ dài cột TENLOAIPHIEU để chứa chuỗi dài không bị cắt cụt
ALTER TABLE PHIEUDATHANG ALTER COLUMN TENLOAIPHIEU NVARCHAR(200);
GO


-- BƯỚC 2: XÓA DỮ LIỆU CŨ THEO THỨ TỰ KHÓA NGOẠI TRÁNH XUNG ĐỘT
-----------------------------------------------------------------
DELETE FROM THANHTOANTHE;
DELETE FROM CHITIETDONHANG;
DELETE FROM DONHANG;
DELETE FROM GIOHANG;
DELETE FROM SANPHAM;
DELETE FROM NHOMSANPHAM;
DELETE FROM PHIEUDATHANG;
DELETE FROM KHACHHANG;
GO


-- BƯỚC 3: NẠP DỮ LIỆU MẪU (DUMMY DATA)
-----------------------------------------------------------------

-- 1. Bảng KHACHHANG (UC01, UC02, UC05)
INSERT INTO KHACHHANG (MAKH, HOTEN, NGAYSINH, CCCD, DIACHI, DIENTHOAI, TENDANGNHAP, MATKHAU, EMAIL) VALUES
('KH01', N'Nguyễn Văn An', '1995-05-12', '079195012345', N'123 Nguyễn Trãi, Quận 1, TP.HCM', '0901112233', 'hoa_nguyen', '123456', 'nguyenvanan@gmail.com'),
('KH02', N'Trần Thị Bình', '1998-08-20', '079198098765', N'456 Lê Văn Việt, TP. Thủ Đức', '0912223344', 'tranbinh', '123456', 'tranthibinh@gmail.com'),
('KH03', N'Lê Hoàng Long', '1990-12-05', '079190011223', N'789 Cách Mạng Tháng 8, Quận 3, TP.HCM', '0988334455', 'hoanglong', '123456', 'lehoanglong@gmail.com');
GO

-- 2. Bảng NHOMSANPHAM (UC03)
INSERT INTO NHOMSANPHAM (MANHOM, TENNHOM) VALUES
('N01', N'Điện thoại & Phụ kiện'),
('N02', N'Laptop & Thiết bị IT'),
('N03', N'Điện gia dụng thông minh');
GO

-- 3. Bảng SANPHAM (UC03)
INSERT INTO SANPHAM (MASP, TENSP, MANHOM, GIABANHIENHANH, SOLUONGTON, MOTA) VALUES
('SP01', N'iPhone 15 Pro Max 256GB', 'N01', 29990000, 50, N'Điện thoại thông minh cao cấp chính hãng Apple'),
('SP02', N'Samsung Galaxy S24 Ultra', 'N01', 26990000, 30, N'Flagship đỉnh cao tích hợp AI của Samsung'),
('SP03', N'Laptop MacBook Air M3 2024', 'N02', 28500000, 20, N'Laptop mỏng nhẹ, hiệu năng mạnh mẽ'),
('SP04', N'Laptop Asus ROG Strix G16', 'N02', 35000000, 15, N'Laptop Gaming cấu hình cực mạnh'),
('SP05', N'Nồi chiên không dầu Philips 7L', 'N03', 3200000, 40, N'Nồi chiên dung tích lớn, công nghệ Rapid Air'),
('SP06', N'Máy lọc không khí Xiaomi Gen 4', 'N03', 2800000, 60, N'Lọc bụi mịn PM2.5, kết nối điện thoại');
GO

-- 4. Bảng PHIEUDATHANG (UC06)
INSERT INTO PHIEUDATHANG (MALOAIPHIEU, TENLOAIPHIEU, DONGIPHIVANCHUYEN) VALUES
('CPN', N'Chuyển phát nhanh tiêu chuẩn (Miễn phí từ 1.000.000đ)', 30000),
('CPNNGAY', N'Chuyển phát nhanh trong ngày (Miễn phí từ 5.000.000đ)', 80000),
('THUONG', N'Vận chuyển thông thường tiết kiệm', 15000);
GO

-- 5. Bảng GIOHANG (UC04)
INSERT INTO GIOHANG (MAKH, MASP, SOLUONG) VALUES
('KH01', 'SP01', 1), 
('KH01', 'SP05', 2), 
('KH02', 'SP03', 1);
GO

-- 6. Bảng DONHANG & CHITIETDONHANG (UC06)
INSERT INTO DONHANG (SODDH, NGAYDATHANG, TONGTRIGIA, PHIGIAOHANG, TENNGUOINHAN, DIACHINHAN, DIENTHOAINHAN, MAKH, MALOAIPHIEU) VALUES
('DH2026060601', GETDATE(), 30020000, 0, N'Nguyễn Văn An', N'123 Nguyễn Trãi, Q.1, TP.HCM', '0901112233', 'KH01', 'CPN');

INSERT INTO CHITIETDONHANG (SODDH, MASP, SOLUONG, DONGIA) VALUES
('DH2026060601', 'SP01', 1, 29990000);
GO

-- 7. Bảng THANHTOANTHE (UC07)
INSERT INTO THANHTOANTHE (MAGIAODICH, SODDH, LOAITHE, SOHIEUTHE, NGAYHETHAN, HOTENCHUTHE, MASOANNINHCSV, TRANGTHAITHANHTOAN) VALUES
('GD2026060601', 'DH2026060601', 'VISA', '4111222233334444', '12/28', N'NGUYEN VAN AN', '123', N'Thành công');
GO